apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7878
      protocol: TCP
      name: http
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}
