apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snipe-it
  namespace: snipe-it
spec:
  interval: 1h
  suspend: true
  chart:
    spec:
      chart: charts/snipe-it
      version: 2.0.4
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      tag: latest
      pullPolicy: Always