apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: squidex
  namespace: squidex
spec:
  interval: 5m
  chart:
    spec:
      chart: squidex7
      version: 1.0.1      
      sourceRef:
        kind: HelmRepository
        name: squidex
        namespace: squidex
  valuesFrom:
    - kind: Secret
      name: github
      valuesKey: "ClientId"
      targetPath: "env.IDENTITY__GITHUBCLIENT"
      optional: false
    - kind: Secret
      name: github
      targetPath: "env.IDENTITY__GITHUBSECRET"
      valuesKey: "ClientSecret"
      optional: false
    - kind: Secret
      name: admin-password
      targetPath: "env.IDENTITY__ADMINPASSWORD"
      valuesKey: "Password"
      optional: false
  values:
    ingress:
      enabled: true
      hostName: squidex.localhost
    image:
      tag: "7.0.2"
    env:
      IDENTITY__ADMINEMAIL: "patrick.magee@live.co.uk"
      URLS__BASEURL: http://squidex.localhost
      IDENTITY__ADMINRECREATE: true
      IDENTITY__ALLOWPASSWORDAUTH: true
      URLS__ENFORCEHTTPS: false
