apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: squidex
spec:
  interval: 5m
  chart:
    spec:
      chart: squidex7
      version: 1.0.1      
      sourceRef:
        kind: HelmRepository
        name: squidex
        namespace: squidex
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    ingress:
      enabled: false
    service:
      port: 8888
      type: "ClusterIP"
    deployment:
      replicaCount: 1
    image:
      tag: "7.0.2"
    env:
      IDENTITY__ADMINEMAIL: "patrick.magee@live.co.uk"
      IDENTITY__ADMINPASSWORD: "password"
      IDENTITY__ADMINRECREATE: true
      IDENTITY__ALLOWPASSWORDAUTH: true
      IDENTITY__LOCKAUTOMATICALLY: true
      URLS__ENFORCEHTTPS: false
