apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/qbittorrent
      appVersion: "4.6.5-r0-ls335"
      version: 1.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/qbittorrent/values.yaml