apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
spec:
  interval: 5m
  chart:
    spec:      
      chart: charts/nzbget
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    volumes:
      - name: config
        hostPath: 
          path: /run/desktop/mnt/host/m/docker/nzbget
          type: Directory      
      - name: downloads
        hostPath: 
          path: /run/desktop/mnt/host/m/docker/downloads/nzbget
          type: Directory