apiVersion: v2
name: asa-server
description: A Helm chart for ARK Survival Ascended Server using Zerschranzer/Linux-ASA-Server-Manager
type: application
version: 2.0.0
appVersion: "latest"
keywords:
  - game-server
  - ark
  - survival
  - ascended
  - zerschranzer
  - proton
maintainers:
  - name: Patrick Magee
sources:
  - https://github.com/Zerschranzer/Linux-ASA-Server-Manager
