# Default values for asa-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ASA Server Configuration
image:
  repository: acekorneya/asa_server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2_1_latest"

nameOverride: ""
fullnameOverride: ""

# Instance configuration
instance:
  name: "asa-server"
  timezone: "America/New_York"

# Server Settings
server:
  # Map settings
  mapName: "TheIsland_WP"  # TheIsland_WP, ScorchedEarth_WP, TheCenter_WP, Aberration_WP, Extinction_WP, Ragnarok_WP (ASA format)
  sessionName: "My ASA Server"
  password: ""  # Server password (leave empty for no password)
  adminPassword: "arkadmin123"
  maxPlayers: 70
  
  # Network configuration
  ports:
    game: 7777
    rcon: 27020
  
  # Game configuration
  battleye: false
  rconEnabled: true
  
  # MOTD (Message of the Day)
  motd:
    enabled: false
    message: "Welcome to my server!"
    duration: 30
  
  # Admin settings
  showAdminCommandsInChat: false
  
  # Cluster settings
  clusterId: ""
  
  # Mods
  modIds: ""
  passiveMods: ""
  
  # Custom server arguments
  customArgs: ""

# API Configuration (AsaApi)
api:
  enabled: false

# Performance and Monitoring
performance:
  cpuOptimization: false
  randomStartupDelay: true
  displayMonitorMessage: false

# Update settings
updates:
  enabled: true
  interval: 24  # hours
  windowStart: "12:00 AM"
  windowEnd: "11:59 PM"
  restartNoticeMinutes: 30

# Resource limits
resources:
  limits:
    cpu: 2
    memory: 16Gi
  requests:
    cpu: 1
    memory: 8Gi

# Persistence
persistence:
  enabled: true
  
  # Storage type: "pvc" for PersistentVolumeClaims or "hostPath" for direct host storage
  type: "pvc"  # Options: "pvc", "hostPath"
  
  # Host paths (only used when type: "hostPath")
  hostPaths:
    serverFiles: "/run/desktop/mnt/host/m/docker/asa-server/server"
    saved: "/run/desktop/mnt/host/m/docker/asa-server/saved"
    cluster: "/run/desktop/mnt/host/m/docker/asa-server/cluster"
    apiLogs: "/run/desktop/mnt/host/m/docker/asa-server/api-logs"
  
  # PVC settings (only used when type: "pvc")
  # Server files volume
  serverFiles:
    size: 50Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  
  # Saved games and config
  saved:
    size: 5Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  
  # Cluster data (if using clusters)
  cluster:
    size: 1Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  
  # API logs (only if API enabled)
  apiLogs:
    size: 1Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  # For local development, you might want to use NodePort or hostPort
  gamePort: 7777
  rconPort: 27020

# Use hostPort for local development (Docker Desktop)
hostPort:
  enabled: true

# Service Account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Pod Security Context
podSecurityContext:
  runAsUser: 7777
  runAsGroup: 7777
  fsGroup: 7777

# Container Security Context  
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 7777
  runAsGroup: 7777

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Pod affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Probes configuration
probes:
  # Startup probe (ARK takes time to start)
  startup:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60
    successThreshold: 1
  
  # Liveness probe
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  
  # Readiness probe
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Extra environment variables
extraEnvVars: []

# Configuration for existing secrets
existingSecret: ""

# Autoscaling (generally not needed for game servers)
autoscaling:
  enabled: false

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false

# 1Password Integration
onePassword:
  enabled: false
  itemPath: ""
  # Keys to retrieve from 1Password item
  adminPasswordKey: "adminPassword"  # Key for SERVER_ADMIN_PASSWORD
  serverPasswordKey: "serverPassword"  # Key for SERVER_PASSWORD (if using server password)
