# Default values for asa-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Replica control - set to 0 to shutdown server
replicaCount: 1

# ASA Server Configuration
image:
  repository: zerschranzer/ark-ascended-base
  pullPolicy: Always  # Always pull to get latest updates
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

# Timezone for the container (optional, defaults to UTC)
timezone: "Europe/London"

# Update settings
update:
  # Whether to run ARK server update/verification during pod startup
  # Set to false to skip update if you know files are already downloaded
  enabled: true
  
# Server Settings (Zerschranzer configuration format)
server:
  # Basic settings
  serverName: "My ASA Server"
  serverPassword: ""  # Server password (leave empty for no password)
  serverAdminPassword: "adminpassword"
  maxPlayers: 70
  
  # Map and world settings
  mapName: "Ragnarok_WP"  # TheIsland_WP, ScorchedEarth_WP, TheCenter_WP, Aberration_WP, Extinction_WP, Ragnarok_WP
  saveDir: "asa-server"  # Must be unique per instance
  
  # Network configuration
  ports:
    game: 7777      # Port
    query: 7778     # QueryPort (typically game port + 1)
    rcon: 27020     # RCONPort
  
  # Mods (ASA uses GameUserSettings.ini, not command-line)
  modIDs: ""  # Comma-separated mod IDs for ActiveMods in GameUserSettings.ini
  
  # Cluster settings
  clusterID: ""  # Leave empty if not using clustering
  
  # Custom start parameters (Zerschranzer format)
  customStartParameters: "-NoBattlEye -crossplay -NoHangDetection"

# Docker image mode - no longer needed with Zerschranzer
# API Configuration (AsaApi) - handled by the base image
# Performance and Monitoring - handled by the base image
# Update settings - handled by the base image

# Resource limits - Following Zerschranzer documentation minimum requirements
resources:
  limits:
    cpu: 4
    memory: 32Gi
  requests:
    cpu: 2
    memory: 16Gi

# Persistence (Zerschranzer architecture)
persistence:
  enabled: true
  
  # Storage type: "pvc" for PersistentVolumeClaims or "hostPath" for direct host storage
  type: "pvc"  # Options: "pvc", "hostPath"
  
  # Host paths (only used when type: "hostPath")
  hostPaths:
    binaries: "/run/desktop/mnt/host/m/docker/asa-server/server-files"  # Shared ARK server binaries
    instance: "/run/desktop/mnt/host/m/docker/asa-server/instance"      # Instance-specific data
  
  # PVC settings (only used when type: "pvc")
  # Shared server binaries volume
  binaries:
    size: 60Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  
  # Instance-specific data (configs, saves, logs)
  instance:
    size: 10Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

# Service configuration
service:
  type: NodePort
  # NodePort configuration - ports will be auto-assigned or can be specified
  # Valid NodePort range: 30000-32767
  nodePorts:
    game: ""      # Auto-assign if empty, or specify port (e.g., 30777)
    query: ""     # Auto-assign if empty, or specify port (e.g., 30778) 
    rcon: ""      # Auto-assign if empty, or specify port (e.g., 30020)
  # Note: Internal ports are defined in server.ports section

# Use hostPort for local development (Docker Desktop)
hostPort:
  enabled: true

# Service Account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Pod Security Context
podSecurityContext:
  runAsUser: 7777
  runAsGroup: 7777
  fsGroup: 7777

# Container Security Context  
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 7777
  runAsGroup: 7777

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Pod affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Probes configuration
probes:
  # Startup probe (ARK takes time to start)
  startup:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60
    successThreshold: 1
  
  # Liveness probe
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  
  # Readiness probe
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Extra environment variables
extraEnvVars: []

# Configuration for existing secrets
existingSecret: ""

# Autoscaling (generally not needed for game servers)
autoscaling:
  enabled: false

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false

# 1Password Integration
onePassword:
  enabled: false
  itemPath: ""
  # Keys to retrieve from 1Password item
  adminPasswordKey: "adminPassword"  # Key for SERVER_ADMIN_PASSWORD
  serverPasswordKey: "serverPassword"  # Key for SERVER_PASSWORD (if using server password)

# Backup configuration
backup:
  enabled: false  # Set to true to enable manual backups
  # Host path where backups will be stored (Docker Desktop WSL path format)
  # This maps to D:\ark-backups on your Windows machine  
  hostPath: "/run/desktop/mnt/host/d/ark-backups"
  # Scheduled backups
  schedule:
    enabled: false  # Set to true to enable scheduled backups
    cron: "0 3 * * *"  # Daily at 3 AM
    retention: 7  # Keep last 7 backups
  # Backup storage (for PVC-based backups within cluster)
  persistence:
    enabled: false
    size: 20Gi
    storageClass: "hostpath"
    accessModes:
      - ReadWriteOnce

# Restore configuration  
restore:
  enabled: false  # Set to true when you want to restore from backup
  restoreBinaries: false  # Restore server files (usually not needed)

# Management tools
management:
  enabled: true
  # Management container image (lightweight with tools)
  image:
    repository: ubuntu
    tag: "22.04"
    pullPolicy: IfNotPresent