replicaCount: 1
image:
  repository: zerschranzer/ark-ascended-base
  tag: "latest"
  pullPolicy: Never # Built locally and not pushed on docker.io

nameOverride: ""
fullnameOverride: ""
timezone: "Europe/London"

update:
  enabled: true
  
server:
  serverName: "My ASA Server"
  serverPassword: ""
  serverAdminPassword: "adminpassword"
  maxPlayers: 70 
  mapName: "Ragnarok_WP"  # TheIsland_WP, ScorchedEarth_WP, TheCenter_WP, Aberration_WP, Extinction_WP, Ragnarok_WP
  saveDir: "asa-server"
  ports:
    game: 7777
    query: 7778
    rcon: 27020    
  clusterID: ""
  customStartParameters: "-NoBattlEye -NoHangDetection"
  
  # ASA ServerSettings - all settings from [ServerSettings] section of GameUserSettings.ini
  # Only includes settings that are compatible with ARK: Survival Ascended
  serverSettings:
    # ModIDs as a YAML list (rendered as CSV in configmap)
    # Use strings to prevent scientific notation for large mod IDs
    modIDs: []  # List of mod IDs (as strings) - e.g., ["928029", "731604991", "1404697612"]
    # Important: Large mod IDs must be strings to avoid scientific notation in YAML
    # Good: ["928029", "731604991", "1404697612"] 
    # Bad:  [928029, 731604991, 1404697612]  # Numbers > 6 digits may become scientific notation
    
    # Basic multipliers
    XPMultiplier: 1.0
    TamingSpeedMultiplier: 1.0
    HarvestAmountMultiplier: 1.0
    ResourcesRespawnPeriodMultiplier: 1.0
    
    # Creature settings
    DinoCharacterFoodDrainMultiplier: 1.0
    DinoCharacterHealthRecoveryMultiplier: 1.0
    DinoCharacterStaminaDrainMultiplier: 1.0
    DinoDamageMultiplier: 1.0
    DinoResistanceMultiplier: 1.0
    DinoCountMultiplier: 1.0
    
    # Player settings
    PlayerCharacterFoodDrainMultiplier: 1.0
    PlayerCharacterHealthRecoveryMultiplier: 1.0
    PlayerCharacterStaminaDrainMultiplier: 1.0
    PlayerCharacterWaterDrainMultiplier: 1.0
    PlayerDamageMultiplier: 1.0
    PlayerResistanceMultiplier: 1.0
    
    # Day/Night cycle
    DayCycleSpeedScale: 1.0
    DayTimeSpeedScale: 1.0
    NightTimeSpeedScale: 1.0
    
    # Quality of life
    AllowFlyerCarryPvE: true
    ShowMapPlayerLocation: true
    EnablePVPGamma: false
    AllowThirdPersonPlayer: true
    ServerCrosshair: true
    
    # Structure settings
    StructureResistanceMultiplier: 1.0
    StructurePickupTimeAfterPlacement: 30.0
    StructurePickupHoldDuration: 0.5
    TheMaxStructuresInRange: 10500
    
    # Advanced settings
    AutoSavePeriodMinutes: 15.0
    DifficultyOffset: 1.0
    OverrideOfficialDifficulty: 0.0  # Set to 5.0 to match official servers (level 150 creatures)
    
    # PvE settings
    serverPVE: false  # Set to true for PvE mode
    DisableStructureDecayPvE: false
    DisableDinoDecayPvE: false
    PvEDinoDecayPeriodMultiplier: 1.0
    
    # Breeding settings (ASA compatible)
    BabyMatureSpeedMultiplier: 1.0
    EggHatchSpeedMultiplier: 1.0
    MatingIntervalMultiplier: 1.0
    BabyCuddleIntervalMultiplier: 1.0
    BabyImprintAmountMultiplier: 1.0
    BabyImprintingStatScaleMultiplier: 1.0
    
    # Item settings
    ItemStackSizeMultiplier: 1.0
    GlobalItemDecompositionTimeMultiplier: 1.0
    GlobalSpoilingTimeMultiplier: 1.0
    
    # Admin settings
    AdminLogging: false
    ServerHardcore: false

resources:
  limits:
    cpu: 4
    memory: 32Gi
  requests:
    cpu: 2
    memory: 16Gi

persistence:
  enabled: true
  type: "pvc"  # Options: "pvc", "hostPath"  
  # Host paths (only used when type: "hostPath")
  hostPaths:
    binaries: "/run/desktop/mnt/host/m/docker/asa-server/server-files"  # Shared ARK server binaries
    instance: "/run/desktop/mnt/host/m/docker/asa-server/instance"      # Instance-specific data
  
  # PVC settings (only used when type: "pvc")
  binaries:
    size: 60Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  
  instance:
    size: 10Gi
    storageClass: ""
    accessModes:
      - ReadWriteOnce

# Service configuration
service:
  type: NodePort
  # NodePort configuration - ports will be auto-assigned or can be specified
  # Valid NodePort range: 30000-32767
  nodePorts:
    game: 30777      # Auto-assign if empty, or specify port (e.g., 30777)
    query: 30778     # Auto-assign if empty, or specify port (e.g., 30778)
    rcon: 30020      # Auto-assign if empty, or specify port (e.g., 30020)
  # Note: Internal ports are defined in server.ports section

# Use hostPort for local development (Docker Desktop)
hostPort:
  enabled: true

# Service Account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Pod Security Context
podSecurityContext:
  runAsUser: 7777
  runAsGroup: 7777
  fsGroup: 7777

# Container Security Context  
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 7777
  runAsGroup: 7777

# Node selection
nodeSelector: {}

# Tolerations
tolerations: []

# Pod affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Probes configuration
probes:
  # Startup probe (ARK takes time to start)
  startup:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60
    successThreshold: 1
  
  # Liveness probe
  liveness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1
  
  # Readiness probe
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Extra environment variables
extraEnvVars: []

# Configuration for existing secrets
existingSecret: ""

# Autoscaling (generally not needed for game servers)
autoscaling:
  enabled: false

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false

# 1Password Integration
onePassword:
  enabled: false
  itemPath: ""
  # Keys to retrieve from 1Password item
  adminPasswordKey: "adminPassword"  # Key for SERVER_ADMIN_PASSWORD
  serverPasswordKey: "serverPassword"  # Key for SERVER_PASSWORD (if using server password)

# Administrator Whitelisting
# Players listed here can use cheat commands automatically without entering a password
# Get ARK IDs by running 'whoami' command in-game console or 'cheat ListPlayers' as admin
adminWhitelist:
  enabled: false  # Set to true to enable admin whitelisting
  # List of ARK IDs (32 character alphanumeric strings for ASA)
  # Each ID should be on its own line in the list
  arkIDs: []
  # Example:
  # arkIDs:
  #   - "1234567890abcdef1234567890abcdef"  # Player 1
  #   - "fedcba0987654321fedcba0987654321"  # Player 2
  #   - "abcdef1234567890abcdef1234567890"  # Player 3

# Backup configuration
backup:
  enabled: false  # Set to true to enable backup functionality
  # Host path where backups will be stored (Docker Desktop WSL path format)
  # This maps to D:\ark-backups on your Windows machine  
  hostPath: "/run/desktop/mnt/host/d/ark-backups"
  # Scheduled backups - if empty/unset, only manual backups available
  schedule: ""  # Set to cron expression (e.g., "0 3 * * *") to enable scheduled backups
  retention: 7  # Keep last N backups (for scheduled backups only)

# Restore configuration  
restore:
  enabled: false  # Set to true when you want to restore from backup
  restoreBinaries: false  # Restore server files (usually not needed)
  restoreInstance: true   # Restore world saves and instance data (usually what you want)
  backupName: ""          # Name of backup directory to restore from (e.g., "backup-20240711-120000")
  hostPath: ""            # Path to backups (defaults to backup.hostPath if not specified)