apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 1h
  chart:
    spec:
      chart: jupyterhub
      version: 3.3.6
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: jupyterhub.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
    proxy:
      secretToken: "89fd0ce1fe8445c797448bf66e08c32711702cff046bda63bb2c174fd7539585"
    singleuser:
      image:
        name: secana/dotnet-interactive
        tag: latest
      storage:
        type: static
        extraVolumes:
          - name: jupyterhub-user-data
            hostPath:
              path: /run/desktop/mnt/host/m/docker/jupyterhub
              type: DirectoryOrCreate