apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: "1.1.3"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: jupyterhub.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  name: proxy-public
                  port:
                    name: http
    proxy:
      secretToken: "89fd0ce1fe8445c797448bf66e08c32711702cff046bda63bb2c174fd7539585"
      service:
        type: ClusterIP
    singleuser:
      image:
        name: secana/dotnet-interactive:latest
        tag: latest
      storage:
        type: hostPath
        extraVolumes:
          - name: jupyterhub-user-data
            hostPath:
              path: /run/desktop/mnt/host/m/docker/jupyterhub
              type: DirectoryOrCreate