apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-monitoring
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: ./manifests/monitoring/kube-prometheus-stack
  timeout: 5m
  prune: true
  suspend: true