apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
  namespace: dagger
spec:
  interval: 24h0m0s
  chart: 
    spec:
      chart: dagger-helm
      sourceRef:
        kind: HelmRepository
        name: dagger-helm-repo
        namespace: dagger