apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
  namespace: dagger
spec:
  interval: 30m
  chart: 
    spec:
      chart: dagger-helm
      sourceRef:
        kind: HelmRepository
        name: dagger-helm-repo
        namespace: dagger
      # values:
        # engine.image.tag: v0.11.7