apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
  namespace: dagger
spec:
  interval: 30m
  chart:
    spec:
      chart: dagger-helm
      version: 0.1.8
      appVersion: v0.11.7
      sourceRef:
        kind: HelmRepository
        name: dagger-helm-repo
        namespace: dagger