apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
  namespace: nzbget
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/nzbget
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      values:
        image:
          tag: latest
