apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
  namespace: nzbget
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/nzbget
      version: 1.2.0
      appVersion: "v24.1-ls144"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/nzbget/values.yaml