apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/nzbget
      version: 1.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/nzbget/values.yaml