apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: hashicorp/vault
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: hashicorp