apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 1h
  chart:
    spec:
      chart: vault
      version: v0.23.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: hashicorp