apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: asa-server
  namespace: asa-server
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/asa-server
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    # Image configuration - use locally built image
    image:
      repository: zerschranzer/ark-ascended-base
      tag: "latest"
      pullPolicy: Never  # Use local image, don't pull from registry
    
    # Update configuration - enable to download ARK server files
    update:
      enabled: true  # Enable to download ARK server files
    
    # Timezone for the container
    timezone: "Europe/London"
    
    # Server Settings - private server for friends (Zerschranzer format)
    server:
      mapName: "Ragnarok_WP"  # Ragnarok - Norse-themed map with ruins, longhouses, and hot springs
      serverName: "RagnarokAdventures"  # No spaces - ARK can have issues with spaces in server names
      serverPassword: "friends123"  # Simple password (will be overridden by 1Password if enabled)  
      serverAdminPassword: "fallback-admin-pass"  # Will be overridden by 1Password if enabled
      maxPlayers: 10  # Good size for friends group
      saveDir: "ragnarokasa"  # Unique save directory name
      
      # Standard ports  
      ports:
        game: 7777
        query: 7778  # Updated to match Zerschranzer default (game port + 1)
        rcon: 27020
      
      # Mods - start with popular ones (updated field name for Zerschranzer)
      modIDs: ""  # No mods for debugging
      
      # Custom start parameters (ASA-valid arguments only)
      customStartParameters: "-NoBattlEye -ServerPlatform=PC  -NoHangDetection -ForceAllowCaveFlyers"
    
    # Use hostPort for external access
    hostPort:
      enabled: true
    
    # Resource limits - Following Zerschranzer documentation (minimum 16Gi RAM)
    # Increased CPU for ARK Ascended startup requirements
    resources:
      limits:
        cpu: 8
        memory: 32Gi
      requests:
        cpu: 4
        memory: 16Gi
    
    # Persistence configuration - use PVC to avoid Docker Desktop permission issues
    persistence:
      enabled: true  # Enable persistence for server files
      type: pvc  # Use PVC to avoid hostPath permission issues on Docker Desktop
      binaries:
        size: 50Gi  # ARK server files are large
        accessModes:
          - ReadWriteOnce
        storageClass: "hostpath"  # Docker Desktop storage class
      instance:
        size: 10Gi  # Instance data (saves, configs, logs)
        accessModes:
          - ReadWriteOnce
        storageClass: "hostpath"  # Docker Desktop storage class
    
    # Security context - proper user/group for ARK server
    podSecurityContext:
      runAsUser: 1000  # Steam user
      runAsGroup: 121  # Steam group
      fsGroup: 121
    
    # Container security context - proper user/group for ARK server
    securityContext:
      runAsUser: 1000
      runAsGroup: 121
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    
    # Service configuration - use NodePort for external access
    service:
      type: NodePort
    
    # Add restart policy for debugging
    restartPolicy: Always
    
    # Probe settings - temporarily disabled for debugging
    probes:
      startup:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 180  # Zerschranzer is more optimized
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60  # 10 minutes total startup time
        successThreshold: 1
      
      liveness:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      
      readiness:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    
    # 1Password Integration for secure password management
    onePassword:
      enabled: true
      itemPath: "vaults/gdthxvzzghri27b3o2dq37rv4u/items/a7eya6ujzbgck5if5q7c5yz7ge"
      adminPasswordKey: "adminPassword"
      serverPasswordKey: "serverPassword"
