apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: asa-server
  namespace: asa-server
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/asa-server
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    # ASA Server Configuration
    instance:
      name: "ragnarok-asa"
      timezone: "America/New_York"
    
    # Server Settings - private server for friends
    server:
      mapName: "Ragnarok_WP"  # Ragnarok - Norse-themed map with ruins, longhouses, and hot springs (available June 2025)
      sessionName: "Ragnarok Adventures"
      password: ""  # Will be overridden by 1Password if enabled
      adminPassword: "fallback-admin-pass"  # Will be overridden by 1Password if enabled
      maxPlayers: 10  # Good size for friends group
      
      # Standard ports
      ports:
        game: 7777
        rcon: 27020
      
      # Game configuration
      battleye: false  # More flexible for private server
      rconEnabled: true
      
      # MOTD
      motd:
        enabled: true
        message: "Welcome to Ragnarok Adventures! Explore the Norse-themed landscape and survive together!"
        duration: 30
      
      # Mods - start with popular ones
      modIds: "731604991,889745138"  # S+ and Awesome SpyGlass
      passiveMods: ""
      
      # Admin settings
      showAdminCommandsInChat: false
      
      # Custom server args for better multiplayer experience
      customArgs: "-ForceAllowCaveFlyers -PreventHibernation"
    
    # Performance settings for stable multiplayer
    performance:
      cpuOptimization: true  # Optimize performance
      randomStartupDelay: false  # Not needed for single server
      displayMonitorMessage: true  # Helpful for monitoring
    
    # Update settings - less frequent for stable gameplay
    updates:
      enabled: true
      interval: 168  # Weekly updates
      windowStart: "02:00 AM"
      windowEnd: "04:00 AM"
      restartNoticeMinutes: 30  # Give players more warning
    
    # Use hostPort for external access
    hostPort:
      enabled: true
    
    # Resource limits for stable multiplayer performance
    resources:
      limits:
        cpu: 3
        memory: 12Gi
      requests:
        cpu: 2
        memory: 8Gi
    
    # Persistence configuration
    persistence:
      enabled: true
      
      # Use hostPath for direct control over storage location
      type: "hostPath"
      
      # Host paths - stored under M drive docker folder
      hostPaths:
        serverFiles: "/run/desktop/mnt/host/m/docker/asa-server/server"
        saved: "/run/desktop/mnt/host/m/docker/asa-server/saved"
        cluster: "/run/desktop/mnt/host/m/docker/asa-server/cluster"
        apiLogs: "/run/desktop/mnt/host/m/docker/asa-server/api-logs"
      
      # PVC settings (not used with hostPath but kept for reference)
      serverFiles:
        size: 60Gi
        storageClass: ""
        accessModes:
          - ReadWriteOnce
      
      saved:
        size: 8Gi
        storageClass: ""
        accessModes:
          - ReadWriteOnce
      
      cluster:
        size: 2Gi
        storageClass: ""
        accessModes:
          - ReadWriteOnce
    
    # Security context for proper file permissions
    podSecurityContext:
      runAsUser: 7777
      runAsGroup: 7777
      fsGroup: 7777
    
    # Service configuration
    service:
      type: ClusterIP
      gamePort: 7777
      rconPort: 27020
    
    # Probe settings - ARK takes time to start, adjusted for multiplayer
    probes:
      startup:
        enabled: true
        initialDelaySeconds: 300  # 5 minutes for server initialization
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 40  # 10 minutes total startup time
        successThreshold: 1
      
      liveness:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      
      readiness:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
    
    # Extra environment variables for Wine/Proton compatibility
    extraEnvVars:
      - name: STEAM_COMPAT_CLIENT_INSTALL_PATH
        value: "/home/pok/.steam/steam"
      - name: DISPLAY
        value: ":0"
    
    # 1Password Integration for secure password management
    onePassword:
      enabled: true
      itemPath: "vaults/gdthxvzzghri27b3o2dq37rv4u/items/a7eya6ujzbgck5if5q7c5yz7ge"
      adminPasswordKey: "adminPassword"
      serverPasswordKey: "serverPassword"
