apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: asa-server
  namespace: asa-server
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/asa-server
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    # Timezone for the container
    timezone: "Europe/London"
    
    # Server Settings - private server for friends (Zerschranzer format)
    server:
      mapName: "Ragnarok_WP"  # Ragnarok - Norse-themed map with ruins, longhouses, and hot springs
      serverName: "Ragnarok Adventures"  # Updated from sessionName to serverName
      serverPassword: ""  # Will be overridden by 1Password if enabled  
      serverAdminPassword: "fallback-admin-pass"  # Will be overridden by 1Password if enabled
      maxPlayers: 10  # Good size for friends group
      saveDir: "ragnarok-asa"  # Unique save directory name
      
      # Standard ports  
      ports:
        game: 7777
        query: 7778  # Updated to match Zerschranzer default (game port + 1)
        rcon: 27020
      
      # Mods - start with popular ones (updated field name for Zerschranzer)
      modIDs: "731604991,889745138"  # S+ and Awesome SpyGlass
      
      # Custom start parameters (Zerschranzer format)
      customStartParameters: "-NoBattlEye -crossplay -NoHangDetection -ForceAllowCaveFlyers -PreventHibernation"
    
    # Use hostPort for external access
    hostPort:
      enabled: true
    
    # Resource limits - Following Zerschranzer documentation (minimum 16Gi RAM)
    resources:
      limits:
        cpu: 4
        memory: 32Gi
      requests:
        cpu: 2
        memory: 16Gi
    
    # Persistence configuration (updated for Zerschranzer architecture)
    persistence:
      enabled: true
      
      # Use hostPath for Docker Desktop development
      type: "hostPath"
      
      # Host paths - Docker Desktop format
      hostPaths:
        binaries: "/run/desktop/mnt/host/m/docker/asa-server/server-files"  # Shared ARK binaries
        instance: "/run/desktop/mnt/host/m/docker/asa-server/instance"      # Instance data
      
      # PVC settings (available for production clusters)
      binaries:
        size: 60Gi
        storageClass: ""
        accessModes:
          - ReadWriteOnce
      
      instance:
        size: 15Gi  # Instance configs, saves, and logs
        storageClass: ""
        accessModes:
          - ReadWriteOnce
    
    # Security context for proper file permissions
    podSecurityContext:
      runAsUser: 7777
      runAsGroup: 7777
      fsGroup: 7777
    
    # Service configuration (simplified for Zerschranzer)
    service:
      type: ClusterIP
    
    # Probe settings - adjusted for Zerschranzer optimizations
    probes:
      startup:
        enabled: true
        initialDelaySeconds: 180  # Zerschranzer is more optimized
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60  # 10 minutes total startup time
        successThreshold: 1
      
      liveness:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      
      readiness:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    
    # 1Password Integration for secure password management
    onePassword:
      enabled: true
      itemPath: "vaults/gdthxvzzghri27b3o2dq37rv4u/items/a7eya6ujzbgck5if5q7c5yz7ge"
      adminPasswordKey: "adminPassword"
      serverPasswordKey: "serverPassword"
