apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: asa-server
  namespace: asa-server
spec:
  interval: 5m  # Check for changes every 5 minutes instead of 1 hour
  # suspend: true  # Uncomment to completely disable this HelmRelease
  # Upgrade settings for faster deployments
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
    force: false  # Set to true for faster upgrades (forces pod replacement)
  chart:
    spec:
      chart: charts/asa-server
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    # Replica control - set to 0 to shutdown server
    replicaCount: 1  # Set to 0 to stop server, 1 to start server
    
    # Image configuration - use locally built image
    image:
      repository: zerschranzer/ark-ascended-base
      tag: "latest"
      pullPolicy: Never
    update:
      enabled: true
    timezone: "Europe/London"
    server:
      mapName: "Ragnarok_WP"  # Ragnarok - Norse-themed map with ruins, longhouses, and hot springs
      serverName: "RagnarokAdventures"  # No spaces - ARK can have issues with spaces in server names
      serverPassword: "friends123"  # Simple password (will be overridden by 1Password if enabled)  
      serverAdminPassword: "fallback-admin-pass"  # Will be overridden by 1Password if enabled
      maxPlayers: 10  # Good size for friends group
      saveDir: "ragnarokasa"  # Unique save directory name
      
      ports:
        game: 7777
        query: 7778
        rcon: 27020
      modIDs: ""  # No mods for debugging
      customStartParameters: "-NoBattlEye -ServerPlatform=PC  -NoHangDetection -ForceAllowCaveFlyers"
    # Disable hostPort since we're using NodePort service
    hostPort:
      enabled: false
    resources:
      limits:
        cpu: 8
        memory: 32Gi
      requests:
        cpu: 4
        memory: 16Gi
    
    persistence:
      enabled: true  # Enable persistence for server files
      type: pvc  # Use PVC to avoid hostPath permission issues on Docker Desktop
      binaries:
        size: 50Gi  # ARK server files are large
        accessModes:
          - ReadWriteOnce
        storageClass: "hostpath"  # Docker Desktop storage class
      instance:
        size: 10Gi  # Instance data (saves, configs, logs)
        accessModes:
          - ReadWriteOnce
        storageClass: "hostpath"  # Docker Desktop storage class
    
    # Security context - proper user/group for ARK server
    podSecurityContext:
      runAsUser: 1000  # Steam user
      runAsGroup: 121  # Steam group
      fsGroup: 121
    
    # Container security context - proper user/group for ARK server
    securityContext:
      runAsUser: 1000
      runAsGroup: 121
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
    
    # Service configuration - use NodePort for external access
    service:
      type: NodePort
      # Optionally specify NodePort numbers (auto-assigned if not specified)
      nodePorts:
        game: 30777    # External port for ARK game traffic (TCP/UDP)
        query: 30778   # External port for ARK query traffic (UDP)
        rcon: 30020    # External port for RCON access (TCP)
    
    # Add restart policy for debugging
    restartPolicy: Always
    
    # Probe settings - temporarily disabled for debugging
    probes:
      startup:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 180  # Zerschranzer is more optimized
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60  # 10 minutes total startup time
        successThreshold: 1
      
      liveness:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      
      readiness:
        enabled: false  # Disabled for debugging
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
    
    # 1Password Integration for secure password management
    onePassword:
      enabled: true
      itemPath: "vaults/gdthxvzzghri27b3o2dq37rv4u/items/a7eya6ujzbgck5if5q7c5yz7ge"
      adminPasswordKey: "adminPassword"
      serverPasswordKey: "serverPassword"

    # Backup configuration
    backup:
      enabled: true
      hostPath: "/run/desktop/mnt/host/d/ark-backups"
      schedule: "0 3 * * *"  # Daily at 3 AM (set to "" to disable scheduled backups)
      retention: 7  # Keep last 7 backups

    # Management tools moved to local PowerShell scripts
    # See charts/asa-server/scripts/ directory
    # management:
    #   enabled: false
