{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "asa-server.fullname" . }}-backups
  labels:
    {{- include "asa-server.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.backup.persistence.accessModes }}
  {{- if .Values.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backup.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
{{- end }}
