apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asa-server.fullname" . }}-config
  labels:
    {{- include "asa-server.labels" . | nindent 4 }}
data:
  # Game.ini - Advanced game configuration (optional)
  Game.ini: |
    # Add custom Game.ini settings here
    # This file is optional and will override default game settings
    # Example:
    # [/script/shootergame.shootergamemode]
    # bPvEDisableFriendlyFire=true
  
  # GameUserSettings.ini - Main server configuration
  GameUserSettings.ini: |
    # GameUserSettings.ini for ARK: Survival Ascended
    [ServerSettings]
    # Basic server settings
    ServerName={{ .Values.server.serverName }}
    {{- if .Values.onePassword.enabled }}
    # Note: Passwords will be set via command line args from 1Password environment variables
    # ServerPassword and ServerAdminPassword are injected at runtime from secrets
    {{- else }}
    {{- if .Values.server.serverPassword }}
    ServerPassword={{ .Values.server.serverPassword }}
    {{- end }}
    ServerAdminPassword={{ .Values.server.serverAdminPassword }}
    {{- end }}
    MaxPlayers={{ .Values.server.maxPlayers }}
    RCONEnabled=True
    RCONPort={{ .Values.server.ports.rcon }}
    
    # Default multipliers (can be customized)
    XPMultiplier=1.0
    TamingSpeedMultiplier=1.0
    HarvestAmountMultiplier=1.0
    ResourcesRespawnPeriodMultiplier=1.0
    
    # Quality of life settings
    AllowFlyerCarryPvE=True
    ShowMapPlayerLocation=True
    EnablePVPGamma=True

    {{- if .Values.server.modIDs }}
    # Mod configuration for ASA
    ActiveMods={{ .Values.server.modIDs }}
    {{- end }}
    
    # Custom settings can be added here
