apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asa-server.fullname" . }}-config
  labels:
    {{- include "asa-server.labels" . | nindent 4 }}
data:
  # Game.ini - Advanced game configuration (optional)
  Game.ini: |
    # Add custom Game.ini settings here
    # This file is optional and will override default game settings
    # Example:
    # [/script/shootergame.shootergamemode]
    # bPvEDisableFriendlyFire=true

  {{- if .Values.adminWhitelist.enabled }}
  # AllowedCheaterAccountIDs.txt - Administrator whitelist
  # Players listed here can use cheat commands without entering admin password
  AllowedCheaterAccountIDs.txt: |
    {{- if .Values.adminWhitelist.arkIDs }}
    {{- range .Values.adminWhitelist.arkIDs }}
    {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
  
  # GameUserSettings.ini - Main server configuration
  GameUserSettings.ini: |
    # GameUserSettings.ini for ARK: Survival Ascended
    [ServerSettings]
    # Basic server settings
    ServerName={{ .Values.server.serverName }}
    {{- if .Values.onePassword.enabled }}
    # Note: Passwords will be set via command line args from 1Password environment variables
    # ServerPassword and ServerAdminPassword are injected at runtime from secrets
    {{- else }}
    {{- if .Values.server.serverPassword }}
    ServerPassword={{ .Values.server.serverPassword }}
    {{- end }}
    ServerAdminPassword={{ .Values.server.serverAdminPassword }}
    {{- end }}
    MaxPlayers={{ .Values.server.maxPlayers }}
    
    {{- if .Values.server.modIDs }}
    # Mod configuration for ASA - converts YAML list to CSV string (no spaces)
    # Template logic: {{range $i, $mod := .Values.server.modIDs}}{{if $i}},{{end}}{{ $mod }}{{end}}
    # Example input:  ["928029", "731604991", "1404697612"] 
    # Example output: ActiveMods=928029,731604991,1404697612
    ActiveMods={{ range $i, $mod := .Values.server.modIDs }}{{if $i}},{{end}}{{ $mod }}{{end}}
    {{- end }}

    {{- if .Values.server.serverSettings }}
    # Comprehensive ServerSettings from values.yaml
    # All settings are ASA-compatible and map to official [ServerSettings] documentation
    {{- range $key, $value := .Values.server.serverSettings }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}
    
    # RCON settings - always enabled for management
    RCONEnabled=true
    {{- if .Values.server.serverSettings.RCONPort }}
    RCONPort={{ .Values.server.serverSettings.RCONPort }}
    {{- else }}
    RCONPort={{ .Values.server.ports.rcon }}
    {{- end }}
    
    # Session settings
    [SessionSettings]
    Port={{ .Values.server.ports.game }}
    QueryPort={{ .Values.server.ports.query }}
    SessionName={{ .Values.server.serverName }}

    # Engine settings  
    [/Script/Engine.GameSession]
    MaxPlayers={{ .Values.server.maxPlayers }}
