apiVersion: v1
kind: Service
metadata:
  name: {{ include "asa-server.fullname" . }}
  labels:
    {{- include "asa-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.ports.game }}
      targetPort: game-tcp
      protocol: TCP
      name: game-tcp
    - port: {{ .Values.server.ports.game }}
      targetPort: game-udp
      protocol: UDP
      name: game-udp
    - port: {{ .Values.server.ports.query }}
      targetPort: query-udp
      protocol: UDP
      name: query-udp
    - port: {{ .Values.server.ports.rcon }}
      targetPort: rcon
      protocol: TCP
      name: rcon
  selector:
    {{- include "asa-server.selectorLabels" . | nindent 4 }}
