replicaCount: 1

image:
  repository: lscr.io/linuxserver/changedetection.io
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 80

container:
  port: 5000

volumes:
  - name: config
    hostPath:
      path: /run/desktop/mnt/host/m/docker/changedetection
      type: Directory

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: changedetection.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
