apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.13.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:      
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      service:
        type: ClusterIP
    operator:
      create: false
    ingress:
      enabled: false