apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.10.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    operator:
      create: true
      connectHost: http://connect.1password.svc.cluster.local
      credentialsSecretName: "op-operator-token"
      watchAllNamespaces: true 