apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.13.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      # The Connect server itself (the API and sync components)
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      service:
        type: ClusterIP
    # Disable the operator in this release since we have it running separately now
    operator:
      create: false
    ingress:
      enabled: false