apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: operator
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.13.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    # Disable the Connect server in this release since we have it in the other release
    connect:
      enabled: false
    # Enable only the operator component
    operator:
      create: true
      token:
        name: "op-operator-token"
        key: "token"
      watchAllNamespaces: true 