apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: 1password
spec:
  interval: 60m
  chart:
    spec:
      chart: 1password/connect
      version: connect-1.10.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password