apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  interval: 60m
  chart:
    spec:
      chart: connect
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      replicas: 1
      credentials: 1password-credentials.json
    operator:
      create: true
      token:
        name: "onepassword-token"
        value: "onepassword-token"
      watchNamespace: []