apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.13.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      create: true
      # Use base64-encoded credentials directly in values
      credentials_base64: "" # This will be set by the setup script
      serviceType: ClusterIP
    operator:
      create: true
      # Use Connect token value directly
      token:
        value: "" # This will be set by the setup script
      watchAllNamespaces: true

# After creating the required secrets, restart the 1password release:
# flux reconcile helmrelease 1password -n 1password