apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password
spec:
  interval: 60m
  chart:
    spec:
      chart: connect
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      replicas: 1
      credentialsKey: "1password-credentials.json"
      credentialsName: 1password-credentials
    operator:
      create: true
      token:
        key: operator.token.value
        name: op-connect-token

