apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: ">= 1.13.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password
  values:
    connect:
      create: true
      credentialsName: op-credentials
      # Create the 1Password credentials secret before applying this release:
      # kubectl create namespace 1password --dry-run=client -o yaml | kubectl apply -f -
      # kubectl create secret generic op-credentials --namespace 1password --from-file=1password-credentials.json=/path/to/1password-credentials.json
      credentialsKey: 1password-credentials.json
      serviceType: ClusterIP
    operator:
      create: true
      # Use Connect token authentication
      token:
        name: onepassword-token
        # Create the connect token secret before applying this release:
        # kubectl create secret generic onepassword-token --namespace 1password --from-literal=token=<your-connect-token>
        key: token
      watchAllNamespaces: true

# After creating the required secrets, restart the 1password release:
# flux reconcile helmrelease 1password -n 1password