apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
  namespace: changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/changedetection
      version: 1.2.2
      appVersion: "0.45.23-ls110"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/changedetection/values.yaml