apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/changedetection
      version: 1.2.2
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/changedetection/values.yaml