apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
  namespace: freshrss
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/freshrss
      version: 1.2.1
      appVersion: "1.24.1-ls230"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/freshrss/values.yaml