apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/freshrss
      version: 1.0.3
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/freshrss/values.yaml