replicaCount: 1

image:
  repository: lscr.io/linuxserver/plex
  imagePullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

plexClaim: "claim-N9aDWsxsWy9dPPPK5j4D"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: plex.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

volumes:
  - name: config
    hostPath:
      path: /run/desktop/mnt/host/m/docker/plex
      type: Directory
  - name: series
    hostPath:
      path: /run/desktop/mnt/host/m/docker/media/series
      type: Directory
  - name: movies
    hostPath:
      path: /run/desktop/mnt/host/m/docker/media/movies
      type: Directory

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
