apiVersion: v1
kind: Service
metadata:
  name: {{ include "stremio.fullname" . }}
  labels:
    {{- include "stremio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11470
      protocol: TCP
      name: http
  selector:
    {{- include "stremio.selectorLabels" . | nindent 4 }}
