apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/sonarr
      version: 1.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/sonarr/values.yaml