apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/sonarr
      version: 1.2.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/sonarr/values.yaml