{{- if .Values.onePassword.enabled -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mastodon.fullname" . }}-secrets
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onePassword.itemPath | quote }}
{{- end }} 