{{- if not .Values.onePassword.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.fullname" . }}-secrets
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ .Values.mastodon.secretKeyBase | b64enc | quote }}
  OTP_SECRET: {{ .Values.mastodon.otpSecret | b64enc | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.mastodon.vapidPrivateKey | b64enc | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.mastodon.vapidPublicKey | b64enc | quote }}
  DB_PASS: {{ .Values.postgres.password | b64enc | quote }}
{{- end }} 