apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stremio
  namespace: stremio
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/stremio
      version: 1.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/stremio/values.yaml