apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stremio
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/stremio
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/stremio/values.yaml