replicaCount: 1

image:
  repository: lscr.io/linuxserver/nzbget
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 80

volumes:
  - name: config
    hostPath: 
      path: /run/desktop/mnt/host/m/docker/nzbget
      type: Directory      
  - name: downloads
    hostPath: 
      path: /run/desktop/mnt/host/m/docker/downloads/nzbget
      type: Directory

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nzbget.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}