replicaCount: 1

image:
  repository: lscr.io/linuxserver/qbittorrent
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 8080

volumes:
  - name: config
    hostPath: 
      path: /run/desktop/mnt/host/m/docker/qbittorrent
      type: Directory
  - name: downloads
    hostPath: 
      path: /run/desktop/mnt/host/m/docker/downloads/qbittorrent
      type: Directory

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
