replicaCount: 1

image:
  repository: lscr.io/linuxserver/snipe-it
  imagePullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}

securityContext:
  runAsNonRoot: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: snipe-it.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

volumes:
  - name: config
    hostPath: 
      path: /run/desktop/mnt/host/m/docker/snipe-it
      type: Directory
  - name: mysql-data
    hostPath:
      path: /run/desktop/mnt/host/m/docker/snipe-it-mysql
      type: Directory

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Insert default app values to fix nil pointer errors in deployment template
appKey: "base64:49HKaO8TY6ZM6JL/TmSlZMz5/iPepcmFxkAdImRzrWg="
appUrl: "http://snipe-it.localhost"

# Append MySQL internal configuration
mysql:
  database: snipeit
  user: snipeit
  password: snipeit
  port: 3306
  host: 127.0.0.1
  image:
    repository: mysql
    tag: "9.2"
    pullPolicy: IfNotPresent