apiVersion: v1
kind: Service
metadata:
  name: {{ include "snipe-it.fullname" . }}
  labels:
    {{- include "snipe-it.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "snipe-it.selectorLabels" . | nindent 4 }}
