apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/sabnzbd
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      tag: latest
