apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/sabnzbd
      version: 1.2.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/sabnzbd/values.yaml