apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orchardcorecms
  namespace: orchardcorecms
spec:
  suspend: true
  interval: 1h
  chart:
    spec:
      chart: charts/orchardcorecms
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 0