apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orchardcorecms
  namespace: orchardcorecms
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/orchardcorecms
      version: 1.0.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/orchardcorecms/values.yaml