apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budge
  namespace: budge
spec:
  interval: 1h
  suspend: true
  chart:
    spec:
      chart: charts/budge
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      tag: latest
