apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budge
  namespace: budge
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/budge
      version: 1.2.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/budge/values.yaml