apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1h
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: charts/plex
      version: 1.2.1
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      valuesFile: charts/plex/values.yaml