apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1h
  suspend: true
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: charts/plex
      version: 2.0.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      values:
        replicaCount: 0
